#!/usr/bin/env python3

# Copyright (c) 2022 Graphcore Ltd. All rights reserved.

'''
A command line tool and library used to determine optimal split points to use
when pipelining a large model.
'''


# Main PopLiner script runs upon import.  This wrapper emulates the one usually
# generated by setuptools.
from popliner import main
