// Dummy pipeline to check that the Jenkins job works

pipeline {
    agent any

    stages {
        stage('Foo') {
            steps {
                echo 'This is a dummy diff job step..'
            }
        }
    }
}

